variable "region" {}
variable "aws_profile" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "key_pair" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}
variable "test_site_url" {}
variable "certificate_arn" {}
variable "principal_identifier" {}